engines:
  fixme:
    enabled: true
  checkstyle:
    enabled: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.MemberNameCheck:
        enabled: true
    channel: "beta"
  pmd:
    enabled: true
    channel: "beta"
ratings:
  paths:
  - "**.java"
exclude_paths:
- "**/test/**/*"
