engines:
  fixme:
    enabled: true
  checkstyle:
    enabled: true
#    config: "checkstyle.xml"
    channel: "beta"
  pmd:
    enabled: true
    channel: "beta"
ratings:
  paths:
  - "**.java"
exclude_paths:
- "**/test/**/*"
