language: android

before_install:
 - chmod +x gradlew
 - wget http://services.gradle.org/distributions/gradle-2.10-bin.zip
 - unzip gradle-2.10-bin.zip
 - export GRADLE_HOME=$PWD/gradle-2.10
 - export PATH=$GRADLE_HOME/bin:$PATH

script: gradle :longstringloader:test

#android:
#  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
#    - platform-tools
#    - tools

#    # The BuildTools version used by your project
#    - build-tools-24.0.2
#
#    # The SDK version used to compile your project
#    - android-24

