language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository
before_install:
 - chmod +x gradlew
script: ./gradlew jacocoTestReleaseUnitTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
